---
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.2.0"
    - PUPPET_GEM_VERSION="~> 3.4.0"
    - PUPPET_GEM_VERSION="~> 3.7.0"
matrix:
  fast_finish: true
notifications:
  email:
    - math.parent@gmail.com
